# Site settings
title: My Awesome Website
email: your-email@example.com
description: >- 
  Welcome to my awesome website built with Jekyll and hosted on GitHub Pages.
  Here you'll find my thoughts on web development, design, and more.
baseurl: "/NessimBenAbbes" # the subpath of your site, e.g. /blog
url: "https://nessimbena.github.io/NessimBenAbbes/" 
twitter_username: yourtwitterhandle
github_username:  yourgithubusername

# Build settings
markdown: kramdown
theme: minima
plugins:
  - jekyll-feed
  - jekyll-seo-tag

# Navigation
header_pages:
  - about.md
  - projects.md
  - blog.md

# Defaults
defaults:
  - scope:
      path: ""
      type: "posts"
    values:
      layout: "post"
      author: "Your Name"
  - scope:
      path: ""
      type: "pages"
    values:
      layout: "page"
  - scope:
      path: ""
    values:
      layout: "default"
